# CMake generated Testfile for 
# Source directory: /home/cdjensen94/Projects/MagicSetEditor2-GenevensiS
# Build directory: /home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/build-windows
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(validate-locales "perl" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/locale/validate_locale.pl" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/src" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/ch-s.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/ch-t.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/da.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/de.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/en.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/es.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/fr.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/it.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/jp.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/ko.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/pl.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/pt-br.mse-locale" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/data/ru.mse-locale")
set_tests_properties(validate-locales PROPERTIES  _BACKTRACE_TRIPLES "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/tests.cmake;8;add_test;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/tests.cmake;0;;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/CMakeLists.txt;383;include;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/CMakeLists.txt;0;")
add_test(script-functions "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/build-windows/magicseteditor.exe" "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/script/script-functions.mse-script")
set_tests_properties(script-functions PROPERTIES  _BACKTRACE_TRIPLES "/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/tests.cmake;14;add_test;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/test/tests.cmake;0;;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/CMakeLists.txt;383;include;/home/cdjensen94/Projects/MagicSetEditor2-GenevensiS/CMakeLists.txt;0;")
