# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/magicseteditor-2.6.0-x86_64
Summary:        Magic Set Editor
Name:           magicseteditor
Version:        2.6.1
Release:        2
PackageBase:    magicseteditor
License:        GPL-2.0-or-later
Group:          Amusements/Games
Vendor:         Continuum Universes Studio


Requires: wxWidgets >= 3.3, boost-regex, hunspell















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename magicseteditor-2.6.0-x86_64.rpm
%define _unpackaged_files_terminate_build 0





%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
/usr/bin/magicseteditor




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 2.6.0-1
  Generated by CPack RPM (no Changelog file were provided)


